### ISSUE TITLE
decompose `get_state` query into parallel subqueries

### ISSUE THREAD

**Issue by john-g-g** [steemit/sbds#110]
Supports
- [ ] common state object properties
  - current_route
  - props
  - tag_idx
  - feed_price 
  - error
- [ ] `/@<account>/transfers`
- [ ] `/@<account>/recent-replies`
- [ ] `/@<account>/posts`
- [ ] `/@<account>/comments`
- [ ] `/@<account>/`
- [ ] `/@<account>/blog`
- [ ] `/@<account>/feed`
- [ ] `/@<account>/@<account_name>`
- [ ] `/witnesses or /~witnesses`
- [ ] `/trending`
- [ ] `/payout`
- [ ] `/payout_comments`
- [ ] `/promoted`
- [ ] `/responses`
- [ ] `/hot`
- [ ] `/votes`
- [ ] `/cashout`
- [ ] `/active`
- [ ] `/created`
- [ ] `/recent`
- [ ] `/tags`

```
{
  "current_route": <url>,
  "props": <get_dynamic_global_properties()>              // basic chain properties. a few keys are relevant
  "tag_idx": {
    "trending": <get_trending_tags().map(name)>           // simple array of trending tags used on homepage etc
  },
  "tags": <get_trending_tags()>,                          // only used for tag "explorer" page
  "content": {*url: post_object}                          // posts keyed by author/permlink
  "accounts": {*name: account_object}                     // relevant accounts keyed by name
  "pow_queue": [],                                        // unused/ignore
  "witnesses": <get_witnesses_by_vote()>,                 // only used for /~witnesses
  "discussion_idx": {....},                               // ordered post keys, keyed by (1) current tag (or ""), (2), active sort (e.g. created/trending)
  "witness_schedule": {<get_witness_schedule_object()>}   // unused/ignore
  "feed_price": {<get_current_median_history_price()>}    // referenced from: wallet, market, and signup_bonus(unused?)
  "error": ""
}
```

**Comment by roadscape** [comment]
Why are we doing this again? Hive handles most of this and get_state needs to be factored out of condenser ASAP anyway

**Comment by roadscape** [comment]
To recap chat - 

Hive handles the posts/tags part of `get_state` using native data, allowing us to stop using tags and follows plugins for steemd. I’m guessing the SBDS implementation would be breaking up `get_state` into constituent subcalls. This is useful for the wallet/transfers case, but we’d need to forward the posts-related calls to hive, which already implements `get_state` (except the transfers case). Essentially.. hive and sbds/ah have mutually exclusive information which condenser expects merged. This needs to be addressed at the root (condenser) level or at the hive/sbds level.

Since the bulk of it is already implemented in hive, if we can remove ah reliance from get_state in condenser I don’t believe we need to build any more get_state compatibility layers.

Condenser issue tracking: https://github.com/steemit/condenser/issues/2244, https://github.com/steemit/condenser/issues/2684
Hive implementation: https://github.com/steemit/hivemind/blob/master/hive/server/condenser_api.py
